# Generated by Django 4.0.2 on 2022-03-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=100)),
                ('duracao', models.IntegerField()),
                ('data_lancamento', models.DateField()),
                ('diretor', models.CharField(max_length=150)),
                ('principais_artistas', models.TextField()),
            ],
        ),
    ]
